FROM php:apache

LABEL maintainer="poeradiredja12@gmail.com"

# Set direktori kerja di dalam container
WORKDIR /var/www/html

# Salin file-file proyek Anda ke dalam container
COPY css/ ./css/
COPY js/ ./js/
COPY data/ ./data/
COPY img/ ./img/
COPY app.php table.html 404.html register.php ./
COPY package-lock.json package.json /usr/src/json/

# Expose port yang akan digunakan oleh server web
EXPOSE 8585

# Perintah untuk menjalankan server web
CMD ["apache2-foreground"]

